Add graph component
the-sortinghat/frontend pull request #20
Opened 2021-03-01 15:42 UTC by erickrodrigs

2021-03-12 22:26 UTC, jooaodanieel requested changes
@erickrodrigs eu fui chato, bem chato com o plugin de grafos. Mas você é o versão não-trumpista do Uncle Bob, rapaz!

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    .attr('d', 'M0,-5L10,0L0,5')
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    .attr('stroke-dasharray', (d) => (d.type === 'async' ? '5,5' : undefined))
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +  graph.selectAll('path').data(links).exit().remove()
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    .attr('class', (d) => 'node')
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    .text((d) => d.name)
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    })
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    })
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +    .on('click', (event, d) => d.onModuleClick())
O que faz esse trecho de código?

2021-03-12 22:26 UTC, jooaodanieel commented on plugins/graph.js
> +
Deixei todos os `O que faz esse trecho de código?` nos comentários deste arquivo porque quero que você pense no seguinte.
A situação dos grafos tá resolvida, certo? O código funciona de acordo, a imagem fica linda.
Supõe o seguinte: daqui 4 meses, você precisa voltar aqui para dar manutenção nesse código, agora as arestas não vão mais ser simples, elas vão precisar ter rótulos e espessuras diferentes para representar o peso daquela ligação.
Onde você muda? Qual o código que tá definindo as arestas? Daqui a 4 meses você não vai saber mais.
Eu sei o motivo pelo qual você usou assim, e eu mesmo faria provavelmente igual -- afinal na demo do d3 tá exatamente assim.
Mas como a gente pode fazer melhor?

2021-03-12 22:26 UTC, jooaodanieel commented on components/Graph.vue
> +    })
Olha que espetáculo que fica o código do componente!
Muito bom 🚀

2021-03-12 23:50 UTC, erickrodrigs commented on plugins/graph.js
> +
Para ver se eu peguei um pouco do espírito da questão, refatorei essa função. A ideia que eu trouxe no próximo commit é tratar a construção do grafo como um builder (que a gente discutiu sobre algumas semanas atrás), definindo funções menores responsáveis por construir cada parte do grafo. Tentei ser explícito no nome das funções para que, depois de algum tempo sem mexer no código, eu consiga entender do que se trata cada uma dessas funções.

2021-03-13 13:12 UTC, jooaodanieel commented on plugins/graph.js
> +
Olha que espetáculo que ficou!

2021-03-13 13:13 UTC, jooaodanieel approved these changes

2021-03-13 16:36 UTC, merged