Add one module page
the-sortinghat/frontend pull request #23
Opened 2021-03-26 20:53 UTC by erickrodrigs

2021-03-26 22:30 UTC, jooaodanieel requested changes

2021-03-26 22:30 UTC, jooaodanieel commented on pages/modules/_id.vue
> +        <h2 class="text-lg">Responsability:</h2>
pequeno typo (que talvez tenha passado batido em outros lugares até)
É `responsibility`, não `responsability` ;)

2021-03-26 22:30 UTC, jooaodanieel commented on pages/modules/_id.vue
> +  },
Que espetáculo!

2021-03-26 22:30 UTC, jooaodanieel commented on pages/modules/_id.vue
> +      }))
Esse é um jeito bem vanilla js de fazer as coisas. É o mais adequado aqui?
Pergunta honesta, pois não sei como faria dada a stack (vue e a lib de grafos lá com canvas)

2021-03-26 22:30 UTC, jooaodanieel commented on plugins/services/module/index.js
> +      },
Eu tenho a sensação de que a métrica aqui é, na realidade, a quantidade de _compartlhamento_ de bancos de dados. Mas não acho que seja algo como "tira essa, coloca compartilhamento", acho que vale colocar as duas.
Podemos validar com a Thati

2021-03-29 17:28 UTC, erickrodrigs commented on pages/modules/_id.vue
> +        <h2 class="text-lg">Responsability:</h2>
Sorry, my bad!

2021-03-29 17:28 UTC, erickrodrigs commented on pages/modules/_id.vue
> +      }))
Sobre isso, eu acredito que esse jeito é bem ok. O que eu preciso fazer é capturar o click em um vértice do grafo dentro do plugin de grafos. Dessa forma eu vejo algumas opções:
I. Passar a função que será executada no click para os componentes filhos como uma propriedade. o que eu não acho legal, porque eu não vejo que o componente de grafo precisaria de uma propriedade chamada 'onClick', por exemplo (porque em teoria somente os vértices e arestas são necessários para criar um grafo de fato).
II. Criar a função dentro do componente de grafo, o que para mim também é uma opção ruim porque eu vou, de certa forma, colocar a implementação específica dessa função dentro de um componente que deveria, a priori, ser o mais genérico possível. Além disso, dado que a implementação dessa função leva para uma outra página (e portanto mexe com as rotas), acredito que ela deva ficar no componente pai de todos (a própria página).
III. Vincular a função de click aos vértices do grafo (como está implementado agora). Isso não cria implementações específicas dentro dos componentes, não necessita passar props a mais para o componente e deixa funções que mexem com rotas dentro do componente página.

Essas foram as formas que eu pensei de fazer isso, você tem alguma outra ideia que evite esses pontos que eu coloquei?

2021-03-29 17:28 UTC, erickrodrigs commented on plugins/services/module/index.js
> +      },
Eu tinha pensado inicialmente em colocar essa métrica porque, dado o número de serviços (ns) e o número de banco de dados (ndb), se ns > nbd, pode significar que eu esteja compartilhando banco de dados. Entretanto, não dá para ter 100% de certeza disso, porque por exemplo eu posso ter um vários serviços usando nenhum banco de dados (o que é bem incomum, porém devemos considerar). Além disso, é legal ter contabilizada essa informação da quantidade de compartilhamento, e do jeito que tá eu acho que seria um trampo maior calcular isso.
Então, acredito que o melhor seja colocar essas duas métricas (como você disse) e fazer esse cálculo no backend, retornando as duas infos pro frontend.

2021-04-01 22:19 UTC, jooaodanieel approved these changes

2021-04-01 23:10 UTC, merged