Add Service Data API
the-sortinghat/frontend pull request #24
Opened 2021-04-02 20:22 UTC by erickrodrigs

2021-04-02 20:36 UTC, erickrodrigs commented
Pensei em colocar também os tópicos/canais que o serviço utiliza, algo como:

`asyncOperations: [ { id: 1, topic: 'lorem_ipsum', broker: 'RabbitMQ' } ]`

Você acha válido @jooaodanieel ?

2021-04-08 21:20 UTC, jooaodanieel commented
> Pensei em colocar também os tópicos/canais que o serviço utiliza, algo como:
> 
> `asyncOperations: [ { id: 1, topic: 'lorem_ipsum', broker: 'RabbitMQ' } ]`
> 
> Você acha válido @jooaodanieel ?

Acho sim! O comentário da Thati na reunião resumiu tudo (por isso vou pedir alterações pra já adicionar)

2021-04-08 21:21 UTC, jooaodanieel requested changes
Faz a parada das operações assíncronas :)

2021-04-08 21:45 UTC, jooaodanieel requested changes

2021-04-08 21:45 UTC, jooaodanieel commented on plugins/services/service/index.js
> +    operations: [
aqui talvez valha a pena a gente deixar como `syncOperations` (combina melhor com o `asyncOperations`)

2021-04-08 21:58 UTC, jooaodanieel approved these changes
Que espetáculo

2021-04-08 22:00 UTC, merged