Fetch data from external source
the-sortinghat/frontend pull request #27
Opened 2021-04-17 23:47 UTC by erickrodrigs

2021-04-22 17:38 UTC, jooaodanieel requested changes

2021-04-22 17:38 UTC, jooaodanieel commented on api/index.js
> +app.get('/services/:id', ServiceController.find)
Eu senti falta aqui de outras rotas
- `GET /systems/:id/modules`
- `GET /systems/:id/metrics`
- `GET /modules/:id/services`
- `GET /modules/:id/metrics`
- `GET /services/:id/metrics`

Com elas a gente pode ter um maior desacoplamento entre os dados requisitados. É um pouco mais custoso, porque exige maior quantidade de requests para obter os mesmos dados, mas acho que é importante para dar autonomia para os componentes.

2021-04-22 17:38 UTC, jooaodanieel commented on pages/systems/_id.vue
>        { source: 5, target: 4, type: 'sync' },
Entendi que esses dados são mocks posteriores à integração com as planilhas.
Eles ainda são necessários?

2021-04-27 19:15 UTC, jooaodanieel requested changes
Eu clonei local para executar e tudo funciona bem, a menos da visualização de serviço.
A tabela de operações assíncronas está vazia, mesmo para serviços que emitem eventos.
Dei uma inspecionada no código para ver se eu encontrava algo estranho, porém não achei a raiz do problema.

...

![localhost_3000_services_3(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/12701604/116299135-af5b3580-a773-11eb-9ae6-bab98d9a6287.png)

2021-04-28 16:38 UTC, erickrodrigs commented
@jooaodanieel eu tinha esquecido de pegar as operações assíncronas, agora acredito estar tudo ok.
Só queria comentar algumas coisas:

1. Acho que esse pull request tá ficando meio grande já hahahaha.
2. To meio perdido com relação a algumas métricas, acho que vale a pena eu conversar com vocês na próxima reunião.
3. Algumas novas métricas que a Thati passou não se encaixam no modelo que nosso componente de métricas aceita. Por exemplo, a métrica de Nome do serviço com maior quantidade de operações (nesse caso não teria um valor mínimo, máximo e etc). Seria legal pensar novamente numa nova estrutura para funcionar nesse caso (sem ideias por enquanto).

De todo modo, pedi um novo review. Qualquer detalhe estranho ou errado no que eu fiz, é só avisar.

2021-05-20 17:27 UTC, jooaodanieel approved these changes

2021-05-20 17:40 UTC, merged